apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: demoapp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/target: {{ .Values.clusterURL }}
    nginx.ingress.kubernetes.io/rewrite-target: /
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
spec:
  rules:
  - host: {{ .Values.appURL }}
    http:
      paths:
      - path: /
        backend:
          serviceName: demoapp-service
          servicePort: 80
  tls:
  - hosts:
    - {{ .Values.appURL }}
    secretName: demoapp-tls-secret
