---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-block-device
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  storageClassName: sata
---
apiVersion: v1
kind: Pod
metadata:
  name: test-block
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeDevices:
      - devicePath: /dev/xvda
        name: test-block-device
  volumes:
  - name: test-block-device
    persistentVolumeClaim:
      claimName: test-block-device
      readOnly: false
