---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sata
provisioner: cinder.csi.openstack.org
parameters:
  type: SATA
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
provisioner: cinder.csi.openstack.org
parameters:
  type: SSD
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sas
provisioner: cinder.csi.openstack.org
parameters:
  type: SAS
