apiVersion: v1
kind: Pod
metadata:
  name: somepod
  namespace: all
spec:
  containers:
    - name: web
      image: mtr.external.otc.telekomcloud.com/dis_usecases/somerepo
  
  imagePullSecrets:
    - name: dis-usecases-dis-ops-pull-secret